using System.Collections.Generic;

namespace Nythera.Services;

public static class LocalizationService
{
    private static readonly Dictionary<string, string> _tr = new()
    {
        { "AppTitle", "Nythera" },
        { "AppDescription", "Masaüstü arka planınız olarak ayarlamak için bir video seçin." },
        { "BrowseVideo", "Video Seç" },
        { "ApplyWallpaper", "Duvar Kağıdını Uygula" },
        { "NoVideoSelected", "Henüz video seçilmedi." },
        { "Settings", "Ayarlar" },
        { "Volume", "Ses:" },
        { "ChooseFit", "Sığdırma:" },
        { "LaunchStartup", "Windows açılışında başlat" },
        { "Theme", "Tema:" },
        { "Language", "Dil (Language):" },
        { "UpdateAvailable", "Yeni bir sürüm mevcut!" },
        { "DownloadUpdate", "İndir ve Güncelle" },
        { "Downloading", "Güncelleme indiriliyor... Lütfen bekleyin." },
        { "Restored", "Geri yüklendi:" },
        { "Selected", "Seçildi:" },
        { "StartupEnabled", "Windows başlangıcında başlatılacak." },
        { "StartupDisabled", "Windows başlangıcında başlatılmayacak." },
        { "On", "Açık" },
        { "Off", "Kapalı" },
        { "OperationCancelled", "İşlem iptal edildi." },
        { "ErrorApplying", "Hata:" },
        { "AboutTitle", "Hakkında" },
        { "AppInfoTitle", "Uygulama Bilgileri" },
        { "AboutAppDesc", "Sisteminizi yormadan masaüstünüzü yüksek kaliteli ve hareketli videolarla canlandıran, performans odaklı yeni nesil duvar kağıdı motoru." },
        { "Feature1", "• Düşük RAM ve CPU kullanımı" },
        { "Feature2", "• Akıllı karanlık/aydınlık tema desteği" },
        { "Feature3", "• Otomatik arka plan güncelleme sistemi" },
        { "Feature4", "• Tam ekran oyun/uygulama algılama ile otomatik duraklatma" },
        { "DeveloperTitle", "Geliştirici" },
        { "DeveloperRole", "Software Developer" },
        { "DeveloperDesc", "Modern masaüstü ve web uygulamaları tasarlayan tutkulu bir yazılım geliştirici." },
        { "GithubButton", "GitHub Profilim" },
        { "LinkedInButton", "LinkedIn" },
        { "EmailButton", "E-Posta" },
        { "MonitorName", "Monitör {0}" },
        { "PreviewAllMonitors", "Önizleme: Tüm Ekranlar (Ana Ekran baz alındı: {0}x{1})" },
        { "PreviewMonitor", "Önizleme: {0} ({1}x{2})" },
        { "MonitorText", "Monitör:" },
        { "AllMonitors", "Tüm Ekranlar" },
        { "Applied", "Uygulandı" },
        { "AllMonitorsShort", "Tümü" },
        { "MonitorShort", "M{0}" },
        { "VideoReady", "Video hazır" },
        { "WallpaperApplied", "Duvar kağıdı uygulandı" },
        { "PlaylistMode", "Slayt Modu:" },
        { "PlaylistInterval", "Değişim Süresi" },
        { "PlaylistOrder", "Çalma Sırası" },
        { "ApplyPlaylist", "Uygula" },
        { "PlaylistApplied", "Çalma listesi ({0} video) başarıyla uygulandı!" },
        { "Min1", "1 Dakika" },
        { "Min5", "5 Dakika" },
        { "Min15", "15 Dakika" },
        { "Min30", "30 Dakika" },
        { "Hour1", "1 Saat" },
        { "Hour3", "3 Saat" },
        { "Hour6", "6 Saat" },
        { "Hour12", "12 Saat" },
        { "Hour24", "24 Saat" },
        { "OrderSeq", "Sırasıyla" },
        { "OrderRnd", "Rastgele" },
        { "PlaybackSpeed", "Oynatma Hızı:" },
        { "Speed05", "0.5x" },
        { "Speed075", "0.75x" },
        { "Speed10", "1.0x (Normal)" },
        { "Speed125", "1.25x" },
        { "Speed15", "1.5x" },
        { "Speed20", "2.0x" }
    };

    private static readonly Dictionary<string, string> _en = new()
    {
        { "AppTitle", "Nythera" },
        { "AppDescription", "Select a video to set as your desktop background." },
        { "BrowseVideo", "Browse Video" },
        { "ApplyWallpaper", "Apply Wallpaper" },
        { "NoVideoSelected", "No video selected." },
        { "Settings", "Settings" },
        { "Volume", "Volume:" },
        { "ChooseFit", "Choose a fit:" },
        { "LaunchStartup", "Launch on Windows Startup" },
        { "Theme", "Theme:" },
        { "Language", "Language:" },
        { "UpdateAvailable", "A new version is available!" },
        { "DownloadUpdate", "Download and Update" },
        { "Downloading", "Downloading update... Please wait." },
        { "Restored", "Restored:" },
        { "Selected", "Selected:" },
        { "StartupEnabled", "Will launch on Windows startup." },
        { "StartupDisabled", "Will not launch on Windows startup." },
        { "On", "On" },
        { "Off", "Off" },
        { "OperationCancelled", "Operation cancelled." },
        { "ErrorApplying", "Error applying:" },
        { "AboutTitle", "About" },
        { "AppInfoTitle", "Application Info" },
        { "AboutAppDesc", "A performance-focused next-generation wallpaper engine that brings your desktop to life with high-quality animated videos without straining your system." },
        { "Feature1", "• Low RAM and CPU usage" },
        { "Feature2", "• Smart dark/light theme support" },
        { "Feature3", "• Automatic background update system" },
        { "Feature4", "• Auto-pause with full-screen game/app detection" },
        { "DeveloperTitle", "Developer" },
        { "DeveloperRole", "Software Developer" },
        { "DeveloperDesc", "A passionate software developer designing modern desktop and web applications." },
        { "GithubButton", "My GitHub Profile" },
        { "LinkedInButton", "LinkedIn" },
        { "EmailButton", "Email" },
        { "MonitorName", "Monitor {0}" },
        { "PreviewAllMonitors", "Preview: All Monitors (Based on Primary: {0}x{1})" },
        { "PreviewMonitor", "Preview: {0} ({1}x{2})" },
        { "MonitorText", "Monitor:" },
        { "AllMonitors", "All Monitors" },
        { "Applied", "Applied" },
        { "AllMonitorsShort", "All" },
        { "MonitorShort", "M{0}" },
        { "VideoReady", "Video ready" },
        { "WallpaperApplied", "Wallpaper applied" },
        { "PlaylistMode", "Slideshow Mode:" },
        { "PlaylistInterval", "Change Interval" },
        { "PlaylistOrder", "Playback Order" },
        { "ApplyPlaylist", "Apply" },
        { "PlaylistApplied", "Playlist ({0} videos) successfully applied!" },
        { "Min1", "1 Minute" },
        { "Min5", "5 Minutes" },
        { "Min15", "15 Minutes" },
        { "Min30", "30 Minutes" },
        { "Hour1", "1 Hour" },
        { "Hour3", "3 Hours" },
        { "Hour6", "6 Hours" },
        { "Hour12", "12 Hours" },
        { "Hour24", "24 Hours" },
        { "OrderSeq", "Sequential" },
        { "OrderRnd", "Random" },
        { "PlaybackSpeed", "Playback Speed:" },
        { "Speed05", "0.5x" },
        { "Speed075", "0.75x" },
        { "Speed10", "1.0x (Normal)" },
        { "Speed125", "1.25x" },
        { "Speed15", "1.5x" },
        { "Speed20", "2.0x" }
    };

    public static string GetString(string key)
    {
        string lang = SettingsService.GetLanguage();
        var dict = lang == "tr" ? _tr : _en;
        
        if (dict.TryGetValue(key, out string value))
            return value;
            
        return key;
    }
}
